// Automaatselt genereeritud
const images = [
  "assets/wallpapers/Angry Sun.png",
  "assets/wallpapers/Antarctic.jpg",
  "assets/wallpapers/Aurora.jpg",
  "assets/wallpapers/Autumn.png",
  "assets/wallpapers/Black-Dog.jpg",
  "assets/wallpapers/Blacky.jpg",
  "assets/wallpapers/Bliss.png",
  "assets/wallpapers/Breeze.png",
  "assets/wallpapers/Bright Moon.jpg",
  "assets/wallpapers/Bright Sky.jpg",
  "assets/wallpapers/Brightest Hour.jpg",
  "assets/wallpapers/Canes.jpg",
  "assets/wallpapers/Chill Night.png",
  "assets/wallpapers/CityKity.jpg",
  "assets/wallpapers/CityLity.jpg",
  "assets/wallpapers/Clean.png",
  "assets/wallpapers/Clouds.png",
  "assets/wallpapers/Cloudy Mountain.jpg",
  "assets/wallpapers/Dandelion.jpg",
  "assets/wallpapers/Dark Clouds.png",
  "assets/wallpapers/Dark Flower.png",
  "assets/wallpapers/Darkest Hour.jpg",
  "assets/wallpapers/debianart/MacOS-Themes-for-Windows/Windows/SFW/MacOS-Themes-for-Windows/Themes/BigSur/Wallpapers/001.jpg",
  "assets/wallpapers/debianart/MacOS-Themes-for-Windows/Windows/SFW/MacOS-Themes-for-Windows/Themes/BigSur/Wallpapers/002.jpg",
  "assets/wallpapers/debianart/MacOS-Themes-for-Windows/Windows/SFW/MacOS-Themes-for-Windows/Themes/BigSur/Wallpapers/003.jpg",
  "assets/wallpapers/debianart/MacOS-Themes-for-Windows/Windows/SFW/MacOS-Themes-for-Windows/Themes/BigSur/Wallpapers/004.jpg",
  "assets/wallpapers/debianart/MacOS-Themes-for-Windows/Windows/SFW/MacOS-Themes-for-Windows/Themes/Catalina/Wallpapers/001.jpg",
  "assets/wallpapers/debianart/MacOS-Themes-for-Windows/Windows/SFW/MacOS-Themes-for-Windows/Themes/Catalina/Wallpapers/002.jpg",
  "assets/wallpapers/debianart/MacOS-Themes-for-Windows/Windows/SFW/MacOS-Themes-for-Windows/Themes/El Capitan/Wallpapers/001.jpg",
  "assets/wallpapers/debianart/MacOS-Themes-for-Windows/Windows/SFW/MacOS-Themes-for-Windows/Themes/High Sierra/Wallpapers/001.jpg",
  "assets/wallpapers/debianart/MacOS-Themes-for-Windows/Windows/SFW/MacOS-Themes-for-Windows/Themes/Jaguar/Wallpapers/001.png",
  "assets/wallpapers/debianart/MacOS-Themes-for-Windows/Windows/SFW/MacOS-Themes-for-Windows/Themes/Leopard/Wallpapers/001.png",
  "assets/wallpapers/debianart/MacOS-Themes-for-Windows/Windows/SFW/MacOS-Themes-for-Windows/Themes/Leopard/Wallpapers/002.jpg",
  "assets/wallpapers/debianart/MacOS-Themes-for-Windows/Windows/SFW/MacOS-Themes-for-Windows/Themes/Lion/Wallpapers/001.png",
  "assets/wallpapers/debianart/MacOS-Themes-for-Windows/Windows/SFW/MacOS-Themes-for-Windows/Themes/Mavericks/Wallpapers/001.jpg",
  "assets/wallpapers/debianart/MacOS-Themes-for-Windows/Windows/SFW/MacOS-Themes-for-Windows/Themes/Mojave/Wallpapers/001.jpg",
  "assets/wallpapers/debianart/MacOS-Themes-for-Windows/Windows/SFW/MacOS-Themes-for-Windows/Themes/Mojave/Wallpapers/002.jpg",
  "assets/wallpapers/debianart/MacOS-Themes-for-Windows/Windows/SFW/MacOS-Themes-for-Windows/Themes/Monterey/Wallpapers/001.jpg",
  "assets/wallpapers/debianart/MacOS-Themes-for-Windows/Windows/SFW/MacOS-Themes-for-Windows/Themes/Monterey/Wallpapers/002.jpg",
  "assets/wallpapers/debianart/MacOS-Themes-for-Windows/Windows/SFW/MacOS-Themes-for-Windows/Themes/Mountain Lion/Wallpapers/001.jpg",
  "assets/wallpapers/debianart/MacOS-Themes-for-Windows/Windows/SFW/MacOS-Themes-for-Windows/Themes/Panther/Wallpapers/001.png",
  "assets/wallpapers/debianart/MacOS-Themes-for-Windows/Windows/SFW/MacOS-Themes-for-Windows/Themes/Puma/Wallpapers/001.png",
  "assets/wallpapers/debianart/MacOS-Themes-for-Windows/Windows/SFW/MacOS-Themes-for-Windows/Themes/Sequoia/Wallpapers/001.jpg",
  "assets/wallpapers/debianart/MacOS-Themes-for-Windows/Windows/SFW/MacOS-Themes-for-Windows/Themes/Sequoia/Wallpapers/002.jpg",
  "assets/wallpapers/debianart/MacOS-Themes-for-Windows/Windows/SFW/MacOS-Themes-for-Windows/Themes/Sierra/Wallpapers/001.jpg",
  "assets/wallpapers/debianart/MacOS-Themes-for-Windows/Windows/SFW/MacOS-Themes-for-Windows/Themes/Snow Leopard/Wallpapers/001.jpg",
  "assets/wallpapers/debianart/MacOS-Themes-for-Windows/Windows/SFW/MacOS-Themes-for-Windows/Themes/Snow Leopard/Wallpapers/002.png",
  "assets/wallpapers/debianart/MacOS-Themes-for-Windows/Windows/SFW/MacOS-Themes-for-Windows/Themes/Sonoma/Wallpapers/001.jpg",
  "assets/wallpapers/debianart/MacOS-Themes-for-Windows/Windows/SFW/MacOS-Themes-for-Windows/Themes/Sonoma/Wallpapers/002.jpg",
  "assets/wallpapers/debianart/MacOS-Themes-for-Windows/Windows/SFW/MacOS-Themes-for-Windows/Themes/Tiger/Wallpapers/001.png",
  "assets/wallpapers/debianart/MacOS-Themes-for-Windows/Windows/SFW/MacOS-Themes-for-Windows/Themes/Ventura/Wallpapers/001.jpg",
  "assets/wallpapers/debianart/MacOS-Themes-for-Windows/Windows/SFW/MacOS-Themes-for-Windows/Themes/Ventura/Wallpapers/002.jpg",
  "assets/wallpapers/debianart/MacOS-Themes-for-Windows/Windows/SFW/MacOS-Themes-for-Windows/Themes/Yosemite/Wallpapers/001.jpg",
  "assets/wallpapers/debianart/Microsoft-Copilottheme/Windows/SFW/Microsoft-Copilot/Themes/Copilot/Wallpapers/Dark.jpg",
  "assets/wallpapers/debianart/Microsoft-Copilottheme/Windows/SFW/Microsoft-Copilot/Themes/Copilot/Wallpapers/Light.jpg",
  "assets/wallpapers/debianart/Microsoft-Copilottheme/Windows/SFW/Microsoft-Copilot/Themes/Copilot/Wallpapers/OLED.jpg",
  "assets/wallpapers/debianart/themeMicrosoft-Surface-Pro/Windows/SFW/Microsoft-Surface-Pro/Themes/Surface Pro/Wallpapers/Bloom/Light.jpg",
  "assets/wallpapers/debianart/themeMicrosoft-Surface-Pro/Windows/SFW/Microsoft-Surface-Pro/Themes/Surface Pro/Wallpapers/Bloom/OLED.jpg",
  "assets/wallpapers/debianart/themeMicrosoft-Surface-Pro/Windows/SFW/Microsoft-Surface-Pro/Themes/Surface Pro/Wallpapers/Graphite/Dark.jpg",
  "assets/wallpapers/debianart/themeMicrosoft-Surface-Pro/Windows/SFW/Microsoft-Surface-Pro/Themes/Surface Pro/Wallpapers/Graphite/Light.jpg",
  "assets/wallpapers/debianart/themeMicrosoft-Surface-Pro/Windows/SFW/Microsoft-Surface-Pro/Themes/Surface Pro/Wallpapers/Platinum/Dark.jpg",
  "assets/wallpapers/debianart/themeMicrosoft-Surface-Pro/Windows/SFW/Microsoft-Surface-Pro/Themes/Surface Pro/Wallpapers/Platinum/Light.jpg",
  "assets/wallpapers/debianart/Wallpapers-SFW-Beautiful-Scenery/desktop/SFW/Beautiful-Scenery/1750480460_3014_34030.png",
  "assets/wallpapers/debianart/Wallpapers-SFW-Beautiful-Scenery/desktop/SFW/Beautiful-Scenery/1750480485_1019_57794.png",
  "assets/wallpapers/debianart/Wallpapers-SFW-Beautiful-Scenery/desktop/SFW/Beautiful-Scenery/1750480504_3865_47983.png",
  "assets/wallpapers/debianart/Wallpapers-SFW-Beautiful-Scenery/desktop/SFW/Beautiful-Scenery/1750480526_725_36644.png",
  "assets/wallpapers/debianart/Wallpapers-SFW-Ghost-in-the-Shell/desktop/SFW/Ghost-in-the-Shell/1750481566_3437_50547.png",
  "assets/wallpapers/debianart/Wallpapers-SFW-Ghost-in-the-Shell/desktop/SFW/Ghost-in-the-Shell/1750481774_1277_58929.png",
  "assets/wallpapers/debianart/Wallpapers-SFW-Ghost-in-the-Shell/desktop/SFW/Ghost-in-the-Shell/1750481890_265_21841.png",
  "assets/wallpapers/debianart/Wallpapers-SFW-Ghost-in-the-Shell/desktop/SFW/Ghost-in-the-Shell/1750482104_9042_47867.png",
  "assets/wallpapers/debianart/Windows-11-Hidden-EDU-Themes/Windows/SFW/Windows-11-Hidden-EDU-Themes/Themes/Flower/Wallpapers/flower (dark).jpg",
  "assets/wallpapers/debianart/Windows-11-Hidden-EDU-Themes/Windows/SFW/Windows-11-Hidden-EDU-Themes/Themes/Flower/Wallpapers/flower (light).jpg",
  "assets/wallpapers/debianart/Windows-11-Hidden-EDU-Themes/Windows/SFW/Windows-11-Hidden-EDU-Themes/Themes/Planets/Wallpapers/planets (dark).jpg",
  "assets/wallpapers/debianart/Windows-11-Hidden-EDU-Themes/Windows/SFW/Windows-11-Hidden-EDU-Themes/Themes/Planets/Wallpapers/planets (light).jpg",
  "assets/wallpapers/debianart/Windows-11-Hidden-EDU-Themes/Windows/SFW/Windows-11-Hidden-EDU-Themes/Themes/Sunset/Wallpapers/sunset (dark).jpg",
  "assets/wallpapers/debianart/Windows-11-Hidden-EDU-Themes/Windows/SFW/Windows-11-Hidden-EDU-Themes/Themes/Sunset/Wallpapers/sunset (light).jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-AU/Wallpaper/AU-olwp1.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-AU/Wallpaper/AU-olwp2.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-AU/Wallpaper/AU-olwp3.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-AU/Wallpaper/AU-olwp4.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-AU/Wallpaper/AU-olwp5.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-AU/Wallpaper/AU-olwp6.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-AU/Wallpaper/AU-wp1.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-AU/Wallpaper/AU-wp2.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-AU/Wallpaper/AU-wp3.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-AU/Wallpaper/AU-wp4.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-AU/Wallpaper/AU-wp5.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-AU/Wallpaper/AU-wp6.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-BR/Wallpaper/BR-olwp1.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-BR/Wallpaper/BR-olwp2.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-BR/Wallpaper/BR-olwp3.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-BR/Wallpaper/BR-olwp4.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-BR/Wallpaper/BR-olwp5.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-BR/Wallpaper/BR-olwp6.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-BR/Wallpaper/BR-wp1.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-BR/Wallpaper/BR-wp2.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-BR/Wallpaper/BR-wp3.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-BR/Wallpaper/BR-wp4.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-BR/Wallpaper/BR-wp5.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-BR/Wallpaper/BR-wp6.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-CA/Wallpaper/CA-olwp1.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-CA/Wallpaper/CA-olwp2.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-CA/Wallpaper/CA-olwp3.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-CA/Wallpaper/CA-olwp4.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-CA/Wallpaper/CA-olwp5.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-CA/Wallpaper/CA-olwp6.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-CA/Wallpaper/CA-wp1.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-CA/Wallpaper/CA-wp2.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-CA/Wallpaper/CA-wp3.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-CA/Wallpaper/CA-wp4.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-CA/Wallpaper/CA-wp5.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-CA/Wallpaper/CA-wp6.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-CN/Wallpaper/CN-olwp1.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-CN/Wallpaper/CN-olwp2.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-CN/Wallpaper/CN-olwp3.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-CN/Wallpaper/CN-olwp4.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-CN/Wallpaper/CN-olwp5.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-CN/Wallpaper/CN-olwp6.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-CN/Wallpaper/CN-wp1.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-CN/Wallpaper/CN-wp2.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-CN/Wallpaper/CN-wp3.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-CN/Wallpaper/CN-wp4.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-CN/Wallpaper/CN-wp5.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-CN/Wallpaper/CN-wp6.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-DE/Wallpaper/DE-olwp1.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-DE/Wallpaper/DE-olwp2.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-DE/Wallpaper/DE-olwp3.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-DE/Wallpaper/DE-olwp4.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-DE/Wallpaper/DE-olwp5.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-DE/Wallpaper/DE-olwp6.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-DE/Wallpaper/DE-wp1.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-DE/Wallpaper/DE-wp2.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-DE/Wallpaper/DE-wp3.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-DE/Wallpaper/DE-wp4.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-DE/Wallpaper/DE-wp5.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-DE/Wallpaper/DE-wp6.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-ES/Wallpaper/ES-olwp1.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-ES/Wallpaper/ES-olwp2.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-ES/Wallpaper/ES-olwp3.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-ES/Wallpaper/ES-olwp4.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-ES/Wallpaper/ES-olwp5.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-ES/Wallpaper/ES-olwp6.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-ES/Wallpaper/ES-wp1.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-ES/Wallpaper/ES-wp2.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-ES/Wallpaper/ES-wp3.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-ES/Wallpaper/ES-wp4.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-ES/Wallpaper/ES-wp5.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-ES/Wallpaper/ES-wp6.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-FR/Wallpaper/FR-olwp1.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-FR/Wallpaper/FR-olwp2.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-FR/Wallpaper/FR-olwp3.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-FR/Wallpaper/FR-olwp4.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-FR/Wallpaper/FR-olwp5.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-FR/Wallpaper/FR-olwp6.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-FR/Wallpaper/FR-wp1.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-FR/Wallpaper/FR-wp2.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-FR/Wallpaper/FR-wp3.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-FR/Wallpaper/FR-wp4.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-FR/Wallpaper/FR-wp5.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-FR/Wallpaper/FR-wp6.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-GB/Wallpaper/GB-wp1.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-GB/Wallpaper/GB-wp2.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-GB/Wallpaper/GB-wp3.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-GB/Wallpaper/GB-wp4.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-GB/Wallpaper/GB-wp5.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-GB/Wallpaper/GB-wp6.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-GB/Wallpaper/UK-olwp1.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-GB/Wallpaper/UK-olwp2.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-GB/Wallpaper/UK-olwp3.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-GB/Wallpaper/UK-olwp4.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-GB/Wallpaper/UK-olwp5.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-GB/Wallpaper/UK-olwp6.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-IN/Wallpaper/IN-olwp1.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-IN/Wallpaper/IN-olwp2.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-IN/Wallpaper/IN-olwp3.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-IN/Wallpaper/IN-olwp4.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-IN/Wallpaper/IN-olwp5.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-IN/Wallpaper/IN-olwp6.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-IN/Wallpaper/IN-wp1.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-IN/Wallpaper/IN-wp2.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-IN/Wallpaper/IN-wp3.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-IN/Wallpaper/IN-wp4.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-IN/Wallpaper/IN-wp5.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-IN/Wallpaper/IN-wp6.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-IT/Wallpaper/IT-olwp1.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-IT/Wallpaper/IT-olwp2.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-IT/Wallpaper/IT-olwp3.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-IT/Wallpaper/IT-olwp4.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-IT/Wallpaper/IT-olwp5.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-IT/Wallpaper/IT-olwp6.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-IT/Wallpaper/IT-wp1.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-IT/Wallpaper/IT-wp2.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-IT/Wallpaper/IT-wp3.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-IT/Wallpaper/IT-wp4.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-IT/Wallpaper/IT-wp5.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-IT/Wallpaper/IT-wp6.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-JP/Wallpaper/JP-olwp1.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-JP/Wallpaper/JP-olwp2.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-JP/Wallpaper/JP-olwp3.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-JP/Wallpaper/JP-olwp4.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-JP/Wallpaper/JP-olwp5.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-JP/Wallpaper/JP-olwp6.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-JP/Wallpaper/JP-wp1.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-JP/Wallpaper/JP-wp2.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-JP/Wallpaper/JP-wp3.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-JP/Wallpaper/JP-wp4.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-JP/Wallpaper/JP-wp5.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-JP/Wallpaper/JP-wp6.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-KR/Wallpaper/KR-olwp1.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-KR/Wallpaper/KR-olwp2.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-KR/Wallpaper/KR-olwp3.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-KR/Wallpaper/KR-olwp4.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-KR/Wallpaper/KR-olwp5.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-KR/Wallpaper/KR-olwp6.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-KR/Wallpaper/KR-wp1.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-KR/Wallpaper/KR-wp2.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-KR/Wallpaper/KR-wp3.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-KR/Wallpaper/KR-wp4.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-KR/Wallpaper/KR-wp5.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-KR/Wallpaper/KR-wp6.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-MX/Wallpaper/MX-olwp1.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-MX/Wallpaper/MX-olwp2.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-MX/Wallpaper/MX-olwp3.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-MX/Wallpaper/MX-olwp4.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-MX/Wallpaper/MX-olwp5.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-MX/Wallpaper/MX-olwp6.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-MX/Wallpaper/MX-wp1.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-MX/Wallpaper/MX-wp2.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-MX/Wallpaper/MX-wp3.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-MX/Wallpaper/MX-wp4.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-MX/Wallpaper/MX-wp5.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-MX/Wallpaper/MX-wp6.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-NL/Wallpaper/NL-olwp1.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-NL/Wallpaper/NL-olwp2.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-NL/Wallpaper/NL-olwp3.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-NL/Wallpaper/NL-olwp4.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-NL/Wallpaper/NL-olwp5.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-NL/Wallpaper/NL-olwp6.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-NL/Wallpaper/NL-wp1.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-NL/Wallpaper/NL-wp2.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-NL/Wallpaper/NL-wp3.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-NL/Wallpaper/NL-wp4.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-NL/Wallpaper/NL-wp5.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-NL/Wallpaper/NL-wp6.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-PL/Wallpaper/PL-olwp1.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-PL/Wallpaper/PL-olwp2.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-PL/Wallpaper/PL-olwp3.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-PL/Wallpaper/PL-olwp4.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-PL/Wallpaper/PL-olwp5.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-PL/Wallpaper/PL-olwp6.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-PL/Wallpaper/PL-wp1.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-PL/Wallpaper/PL-wp2.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-PL/Wallpaper/PL-wp3.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-PL/Wallpaper/PL-wp4.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-PL/Wallpaper/PL-wp5.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-PL/Wallpaper/PL-wp6.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-RU/Wallpaper/RU-olwp1.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-RU/Wallpaper/RU-olwp2.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-RU/Wallpaper/RU-olwp3.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-RU/Wallpaper/RU-olwp4.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-RU/Wallpaper/RU-olwp5.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-RU/Wallpaper/RU-olwp6.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-RU/Wallpaper/RU-wp1.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-RU/Wallpaper/RU-wp2.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-RU/Wallpaper/RU-wp3.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-RU/Wallpaper/RU-wp4.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-RU/Wallpaper/RU-wp5.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-RU/Wallpaper/RU-wp6.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-TR/Wallpaper/TR-olwp1.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-TR/Wallpaper/TR-olwp2.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-TR/Wallpaper/TR-olwp3.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-TR/Wallpaper/TR-olwp4.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-TR/Wallpaper/TR-olwp5.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-TR/Wallpaper/TR-wp1.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-TR/Wallpaper/TR-wp2.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-TR/Wallpaper/TR-wp3.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-TR/Wallpaper/TR-wp4.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-TR/Wallpaper/TR-wp5.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-TR/Wallpaper/TR-wp6.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-TW/Wallpaper/TW-olwp1.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-TW/Wallpaper/TW-olwp2.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-TW/Wallpaper/TW-olwp3.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-TW/Wallpaper/TW-olwp4.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-TW/Wallpaper/TW-olwp5.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-TW/Wallpaper/TW-olwp6.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-TW/Wallpaper/TW-wp1.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-TW/Wallpaper/TW-wp2.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-TW/Wallpaper/TW-wp3.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-TW/Wallpaper/TW-wp4.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-TW/Wallpaper/TW-wp5.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-TW/Wallpaper/TW-wp6.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-US/Wallpaper/US-olwp1.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-US/Wallpaper/US-olwp2.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-US/Wallpaper/US-olwp3.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-US/Wallpaper/US-olwp4.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-US/Wallpaper/US-olwp5.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-US/Wallpaper/US-olwp6.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-US/Wallpaper/US-wp1.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-US/Wallpaper/US-wp2.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-US/Wallpaper/US-wp3.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-US/Wallpaper/US-wp4.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-US/Wallpaper/US-wp5.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-US/Wallpaper/US-wp6.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-ZA/Wallpaper/ZA-olwp1.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-ZA/Wallpaper/ZA-olwp2.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-ZA/Wallpaper/ZA-olwp3.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-ZA/Wallpaper/ZA-olwp4.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-ZA/Wallpaper/ZA-olwp5.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-ZA/Wallpaper/ZA-olwp6.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-ZA/Wallpaper/ZA-wp1.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-ZA/Wallpaper/ZA-wp2.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-ZA/Wallpaper/ZA-wp3.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-ZA/Wallpaper/ZA-wp4.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-ZA/Wallpaper/ZA-wp5.jpg",
  "assets/wallpapers/debianart/Windows-7-MCT-Themes/Windows/SFW/Windows-7-MCT-Themes/MCT/MCT-ZA/Wallpaper/ZA-wp6.jpg",
  "assets/wallpapers/debianart/Windows-SFW-Classic-11/Windows/SFW/Classic-11/Themes/Classic 11/Wallpapers/Classic 11.png",
  "assets/wallpapers/Deep Forest.jpg",
  "assets/wallpapers/Doremon.jpg",
  "assets/wallpapers/Enderman.png",
  "assets/wallpapers/Evening Clouds.jpg",
  "assets/wallpapers/Evening Mountain.jpg",
  "assets/wallpapers/expert.png",
  "assets/wallpapers/favicon.jpg",
  "assets/wallpapers/Flower 1.jpg",
  "assets/wallpapers/Flower 2.jpg",
  "assets/wallpapers/Flower 3.jpg",
  "assets/wallpapers/Flower 4.jpg",
  "assets/wallpapers/Flower.jpg",
  "assets/wallpapers/Flower.png",
  "assets/wallpapers/Foggy Evening.jpg",
  "assets/wallpapers/Foggy Island.jpg",
  "assets/wallpapers/Foresty Mountain.jpg",
  "assets/wallpapers/Gradient.png",
  "assets/wallpapers/Ice.png",
  "assets/wallpapers/Into the Trees.jpg",
  "assets/wallpapers/Kitty.jpg",
  "assets/wallpapers/Milky Way 2.png",
  "assets/wallpapers/Milky Way 3.png",
  "assets/wallpapers/Milky Way 4.png",
  "assets/wallpapers/Milky Way 5.png",
  "assets/wallpapers/Milky Way.png",
  "assets/wallpapers/Moon.jpg",
  "assets/wallpapers/Moonlight.png",
  "assets/wallpapers/Mountain.png",
  "assets/wallpapers/Mountan.jpg",
  "assets/wallpapers/MyImage.jpg",
  "assets/wallpapers/Nebula-2.png",
  "assets/wallpapers/Nebula-3.jpg",
  "assets/wallpapers/Nebula.jpg",
  "assets/wallpapers/Night Mountains.png",
  "assets/wallpapers/Northern Forest.png",
  "assets/wallpapers/Ocean Rocks.jpg",
  "assets/wallpapers/Peaceful River.png",
  "assets/wallpapers/Peak.jpg",
  "assets/wallpapers/peakpx (4).jpg",
  "assets/wallpapers/Plants.jpg",
  "assets/wallpapers/Polar Night.jpg",
  "assets/wallpapers/Port City.jpg",
  "assets/wallpapers/Purple Sky.png",
  "assets/wallpapers/Reflection 2.jpg",
  "assets/wallpapers/Reflection.jpg",
  "assets/wallpapers/Rementerendermanch.png",
  "assets/wallpapers/Rin.png",
  "assets/wallpapers/Rocks.jpg",
  "assets/wallpapers/Sad Tree.jpg",
  "assets/wallpapers/Sky High.png",
  "assets/wallpapers/Sky.jpg",
  "assets/wallpapers/Sky.png",
  "assets/wallpapers/Snowy Forest.jpg",
  "assets/wallpapers/Snowy Spruce.jpg",
  "assets/wallpapers/Starry Horizon.jpg",
  "assets/wallpapers/Sunlight.jpg",
  "assets/wallpapers/Sunrise.png",
  "assets/wallpapers/Sunset.png",
  "assets/wallpapers/Tent.png",
  "assets/wallpapers/The Ninth Wave.png",
  "assets/wallpapers/Torn.jpg",
  "assets/wallpapers/Tulip.png",
  "assets/wallpapers/usertile16.bmp",
  "assets/wallpapers/Wallpaper/4K/Wallpaper/Windows/img0_1024x768.jpg",
  "assets/wallpapers/Wallpaper/4K/Wallpaper/Windows/img0_1200x1920.jpg",
  "assets/wallpapers/Wallpaper/4K/Wallpaper/Windows/img0_1366x768.jpg",
  "assets/wallpapers/Wallpaper/4K/Wallpaper/Windows/img0_1600x2560.jpg",
  "assets/wallpapers/Wallpaper/4K/Wallpaper/Windows/img0_2160x3840.jpg",
  "assets/wallpapers/Wallpaper/4K/Wallpaper/Windows/img0_2560x1600.jpg",
  "assets/wallpapers/Wallpaper/4K/Wallpaper/Windows/img0_3840x2160.jpg",
  "assets/wallpapers/Wallpaper/4K/Wallpaper/Windows/img0_768x1024.jpg",
  "assets/wallpapers/Wallpaper/4K/Wallpaper/Windows/img0_768x1366.jpg",
  "assets/wallpapers/Wallpaper/Windows/img0.jpg",
  "assets/wallpapers/Wallpaper/Windows10/img1.jpg",
  "assets/wallpapers/Wallpaper/Windows10/img2.jpg",
  "assets/wallpapers/Wallpaper/Windows10/img3.jpg",
  "assets/wallpapers/Wallpaper/Windows10/img4.jpg",
  "assets/wallpapers/Wallpaper/Windows10/img5.jpg",
  "assets/wallpapers/wallpaperbetter.jpg",
  "assets/wallpapers/Watch.jpeg",
  "assets/wallpapers/Waves.jpg",
  "assets/wallpapers/Wheat.jpg",
  "assets/wallpapers/White Nebula.jpg",
  "assets/wallpapers/Windows 10 cloud pc.jpg",
  "assets/wallpapers/Windows 7.png",
  "assets/wallpapers/windows-10/img0_3840x2160.jpg",
  "assets/wallpapers/windows-10/img1.jpg",
  "assets/wallpapers/windows-10/img10.jpg",
  "assets/wallpapers/windows-10/img100.jpg",
  "assets/wallpapers/windows-10/img101.png",
  "assets/wallpapers/windows-10/img102.jpg",
  "assets/wallpapers/windows-10/img103.png",
  "assets/wallpapers/windows-10/img104.jpg",
  "assets/wallpapers/windows-10/img105.jpg",
  "assets/wallpapers/windows-10/img11.jpg",
  "assets/wallpapers/windows-10/img12.jpg",
  "assets/wallpapers/windows-10/img2.jpg",
  "assets/wallpapers/windows-10/img3.jpg",
  "assets/wallpapers/windows-10/img4.jpg",
  "assets/wallpapers/windows-10/img7.jpg",
  "assets/wallpapers/windows-10/img8.jpg",
  "assets/wallpapers/windows-10/img9.jpg",
  "assets/wallpapers/windows-10-green-wallpaper.jpg",
  "assets/wallpapers/windows-11/img0.jpg",
  "assets/wallpapers/windows-11/img0_1920x1200.jpg",
  "assets/wallpapers/windows-11/img100.jpg",
  "assets/wallpapers/windows-11/img101.jpg",
  "assets/wallpapers/windows-11/img102.jpg",
  "assets/wallpapers/windows-11/img103.jpg",
  "assets/wallpapers/windows-11/img104.jpg",
  "assets/wallpapers/windows-11/img105.jpg",
  "assets/wallpapers/windows-11/img14.jpg",
  "assets/wallpapers/windows-11/img19.jpg",
  "assets/wallpapers/windows-11/img19_1920x1200.jpg",
  "assets/wallpapers/windows-11/img20.jpg",
  "assets/wallpapers/windows-11/img21.jpg",
  "assets/wallpapers/windows-11/img22.jpg",
  "assets/wallpapers/windows-11/img23.jpg",
  "assets/wallpapers/windows-11/img24.jpg",
  "assets/wallpapers/windows-11/img25.jpg",
  "assets/wallpapers/windows-11/img26.jpg",
  "assets/wallpapers/windows-11/img27.jpg",
  "assets/wallpapers/windows-11/img28.jpg",
  "assets/wallpapers/windows-11/img29.jpg",
  "assets/wallpapers/windows-11/img30.jpg",
  "assets/wallpapers/windows-11/img31.jpg",
  "assets/wallpapers/windows-11/img32.jpg",
  "assets/wallpapers/windows-11/img33.jpg",
  "assets/wallpapers/windows-11/img34.jpg",
  "assets/wallpapers/windows-11/img35.jpg",
  "assets/wallpapers/windows-11/img50.jpg",
  "assets/wallpapers/windows-11/TouchKeyboardThemeDark000.jpg",
  "assets/wallpapers/windows-11/TouchKeyboardThemeDark001.jpg",
  "assets/wallpapers/windows-11/TouchKeyboardThemeDark002.jpg",
  "assets/wallpapers/windows-11/TouchKeyboardThemeDark003.jpg",
  "assets/wallpapers/windows-11/TouchKeyboardThemeLight000.jpg",
  "assets/wallpapers/windows-11/TouchKeyboardThemeLight001.jpg",
  "assets/wallpapers/windows-11/TouchKeyboardThemeLight002.jpg",
  "assets/wallpapers/windows-11/TouchKeyboardThemeLight003.jpg",
  "assets/wallpapers/windows-7/img0.jpg",
  "assets/wallpapers/windows-7/img1.jpg",
  "assets/wallpapers/windows-7/img10.jpg",
  "assets/wallpapers/windows-7/img11.jpg",
  "assets/wallpapers/windows-7/img12.jpg",
  "assets/wallpapers/windows-7/img13.jpg",
  "assets/wallpapers/windows-7/img14.jpg",
  "assets/wallpapers/windows-7/img15.jpg",
  "assets/wallpapers/windows-7/img16.jpg",
  "assets/wallpapers/windows-7/img17.jpg",
  "assets/wallpapers/windows-7/img18.jpg",
  "assets/wallpapers/windows-7/img19.jpg",
  "assets/wallpapers/windows-7/img2.jpg",
  "assets/wallpapers/windows-7/img20.jpg",
  "assets/wallpapers/windows-7/img21.jpg",
  "assets/wallpapers/windows-7/img22.jpg",
  "assets/wallpapers/windows-7/img23.jpg",
  "assets/wallpapers/windows-7/img24.jpg",
  "assets/wallpapers/windows-7/img25.jpg",
  "assets/wallpapers/windows-7/img26.jpg",
  "assets/wallpapers/windows-7/img27.jpg",
  "assets/wallpapers/windows-7/img28.jpg",
  "assets/wallpapers/windows-7/img29.jpg",
  "assets/wallpapers/windows-7/img3.jpg",
  "assets/wallpapers/windows-7/img30.jpg",
  "assets/wallpapers/windows-7/img4.jpg",
  "assets/wallpapers/windows-7/img5.jpg",
  "assets/wallpapers/windows-7/img6.jpg",
  "assets/wallpapers/windows-7/img7.jpg",
  "assets/wallpapers/windows-7/img8.jpg",
  "assets/wallpapers/windows-7/img9.jpg",
  "assets/wallpapers/windows-7-red-wallpapers-lerteer.jpg",
  "assets/wallpapers/windows-7-red-wallpapers.jpg",
  "assets/wallpapers/windows-8/img0.jpg",
  "assets/wallpapers/windows-8/img1.jpg",
  "assets/wallpapers/windows-8/img10.jpg",
  "assets/wallpapers/windows-8/img100.png",
  "assets/wallpapers/windows-8/img101.jpg",
  "assets/wallpapers/windows-8/img102.png",
  "assets/wallpapers/windows-8/img103.jpg",
  "assets/wallpapers/windows-8/img104.jpg",
  "assets/wallpapers/windows-8/img105.jpg",
  "assets/wallpapers/windows-8/img11.jpg",
  "assets/wallpapers/windows-8/img12.jpg",
  "assets/wallpapers/windows-8/img2.jpg",
  "assets/wallpapers/windows-8/img3.jpg",
  "assets/wallpapers/windows-8/img4.jpg",
  "assets/wallpapers/windows-8/img5.jpg",
  "assets/wallpapers/windows-8/img6.jpg",
  "assets/wallpapers/windows-8/img7.jpg",
  "assets/wallpapers/windows-8/img8.jpg",
  "assets/wallpapers/windows-8/img9.jpg",
  "assets/wallpapers/Windows-Bombob-theme.jpg",
  "assets/wallpapers/windows-vista/img1.jpg",
  "assets/wallpapers/windows-vista/img10.jpg",
  "assets/wallpapers/windows-vista/img11.jpg",
  "assets/wallpapers/windows-vista/img12.jpg",
  "assets/wallpapers/windows-vista/img13.jpg",
  "assets/wallpapers/windows-vista/img14.jpg",
  "assets/wallpapers/windows-vista/img15.jpg",
  "assets/wallpapers/windows-vista/img16.jpg",
  "assets/wallpapers/windows-vista/img17.jpg",
  "assets/wallpapers/windows-vista/img18.jpg",
  "assets/wallpapers/windows-vista/img19.jpg",
  "assets/wallpapers/windows-vista/img2.jpg",
  "assets/wallpapers/windows-vista/img20.jpg",
  "assets/wallpapers/windows-vista/img21.jpg",
  "assets/wallpapers/windows-vista/img22.jpg",
  "assets/wallpapers/windows-vista/img23.jpg",
  "assets/wallpapers/windows-vista/img24.jpg",
  "assets/wallpapers/windows-vista/img25.jpg",
  "assets/wallpapers/windows-vista/img26.jpg",
  "assets/wallpapers/windows-vista/img27.jpg",
  "assets/wallpapers/windows-vista/img28.jpg",
  "assets/wallpapers/windows-vista/img29.jpg",
  "assets/wallpapers/windows-vista/img3.jpg",
  "assets/wallpapers/windows-vista/img30.jpg",
  "assets/wallpapers/windows-vista/img31.jpg",
  "assets/wallpapers/windows-vista/img32.jpg",
  "assets/wallpapers/windows-vista/img33.jpg",
  "assets/wallpapers/windows-vista/img34.jpg",
  "assets/wallpapers/windows-vista/img35.jpg",
  "assets/wallpapers/windows-vista/img36.jpg",
  "assets/wallpapers/windows-vista/img4.jpg",
  "assets/wallpapers/windows-vista/img5.jpg",
  "assets/wallpapers/windows-vista/img6.jpg",
  "assets/wallpapers/windows-vista/img7.jpg",
  "assets/wallpapers/windows-vista/img8.jpg",
  "assets/wallpapers/windows-vista/img9.jpg",
  "assets/wallpapers/windows-xp/Ascent.jpg",
  "assets/wallpapers/windows-xp/Autumn.jpg",
  "assets/wallpapers/windows-xp/Azul.jpg",
  "assets/wallpapers/windows-xp/Bliss.bmp",
  "assets/wallpapers/windows-xp/Crystal.jpg",
  "assets/wallpapers/windows-xp/Follow.jpg",
  "assets/wallpapers/windows-xp/Friend.jpg",
  "assets/wallpapers/windows-xp/Home.jpg",
  "assets/wallpapers/windows-xp/Moon flower.jpg",
  "assets/wallpapers/windows-xp/Peace.jpg",
  "assets/wallpapers/windows-xp/Power.jpg",
  "assets/wallpapers/windows-xp/Purple flower.jpg",
  "assets/wallpapers/windows-xp/Radiance.jpg",
  "assets/wallpapers/windows-xp/Red moon desert.jpg",
  "assets/wallpapers/windows-xp/Ripple.jpg",
  "assets/wallpapers/windows-xp/Stonehenge.jpg",
  "assets/wallpapers/windows-xp/Tulips.jpg",
  "assets/wallpapers/windows-xp/Vortec space.jpg",
  "assets/wallpapers/windows-xp/Wind.jpg",
  "assets/wallpapers/windows-xp/Windows XP.jpg",
  "assets/wallpapers/windows11-light-red.jpg",
  "assets/wallpapers/windows11-red-dark.jpg",
  "assets/wallpapers/Windows9-wm0.jpg",
  "assets/wallpapers/Windows_7_SP1_x64_Ultimate_Extreme Nature/Extreme Nature (1).jpg",
  "assets/wallpapers/Windows_7_SP1_x64_Ultimate_Extreme Nature/Extreme Nature (10).jpg",
  "assets/wallpapers/Windows_7_SP1_x64_Ultimate_Extreme Nature/Extreme Nature (11).jpg",
  "assets/wallpapers/Windows_7_SP1_x64_Ultimate_Extreme Nature/Extreme Nature (12).jpg",
  "assets/wallpapers/Windows_7_SP1_x64_Ultimate_Extreme Nature/Extreme Nature (13).jpg",
  "assets/wallpapers/Windows_7_SP1_x64_Ultimate_Extreme Nature/Extreme Nature (14).jpg",
  "assets/wallpapers/Windows_7_SP1_x64_Ultimate_Extreme Nature/Extreme Nature (15).jpg",
  "assets/wallpapers/Windows_7_SP1_x64_Ultimate_Extreme Nature/Extreme Nature (16).jpg",
  "assets/wallpapers/Windows_7_SP1_x64_Ultimate_Extreme Nature/Extreme Nature (17).jpg",
  "assets/wallpapers/Windows_7_SP1_x64_Ultimate_Extreme Nature/Extreme Nature (18).jpg",
  "assets/wallpapers/Windows_7_SP1_x64_Ultimate_Extreme Nature/Extreme Nature (19).jpg",
  "assets/wallpapers/Windows_7_SP1_x64_Ultimate_Extreme Nature/Extreme Nature (2).jpg",
  "assets/wallpapers/Windows_7_SP1_x64_Ultimate_Extreme Nature/Extreme Nature (20).jpg",
  "assets/wallpapers/Windows_7_SP1_x64_Ultimate_Extreme Nature/Extreme Nature (21).jpg",
  "assets/wallpapers/Windows_7_SP1_x64_Ultimate_Extreme Nature/Extreme Nature (22).jpg",
  "assets/wallpapers/Windows_7_SP1_x64_Ultimate_Extreme Nature/Extreme Nature (23).jpg",
  "assets/wallpapers/Windows_7_SP1_x64_Ultimate_Extreme Nature/Extreme Nature (24).jpg",
  "assets/wallpapers/Windows_7_SP1_x64_Ultimate_Extreme Nature/Extreme Nature (25).jpg",
  "assets/wallpapers/Windows_7_SP1_x64_Ultimate_Extreme Nature/Extreme Nature (26).jpg",
  "assets/wallpapers/Windows_7_SP1_x64_Ultimate_Extreme Nature/Extreme Nature (27).jpg",
  "assets/wallpapers/Windows_7_SP1_x64_Ultimate_Extreme Nature/Extreme Nature (28).jpg",
  "assets/wallpapers/Windows_7_SP1_x64_Ultimate_Extreme Nature/Extreme Nature (29).jpg",
  "assets/wallpapers/Windows_7_SP1_x64_Ultimate_Extreme Nature/Extreme Nature (3).jpg",
  "assets/wallpapers/Windows_7_SP1_x64_Ultimate_Extreme Nature/Extreme Nature (30).jpg",
  "assets/wallpapers/Windows_7_SP1_x64_Ultimate_Extreme Nature/Extreme Nature (31).jpg",
  "assets/wallpapers/Windows_7_SP1_x64_Ultimate_Extreme Nature/Extreme Nature (32).jpg",
  "assets/wallpapers/Windows_7_SP1_x64_Ultimate_Extreme Nature/Extreme Nature (33).jpg",
  "assets/wallpapers/Windows_7_SP1_x64_Ultimate_Extreme Nature/Extreme Nature (34).jpg",
  "assets/wallpapers/Windows_7_SP1_x64_Ultimate_Extreme Nature/Extreme Nature (35).jpg",
  "assets/wallpapers/Windows_7_SP1_x64_Ultimate_Extreme Nature/Extreme Nature (36).jpg",
  "assets/wallpapers/Windows_7_SP1_x64_Ultimate_Extreme Nature/Extreme Nature (37).jpg",
  "assets/wallpapers/Windows_7_SP1_x64_Ultimate_Extreme Nature/Extreme Nature (38).jpg",
  "assets/wallpapers/Windows_7_SP1_x64_Ultimate_Extreme Nature/Extreme Nature (39).jpg",
  "assets/wallpapers/Windows_7_SP1_x64_Ultimate_Extreme Nature/Extreme Nature (4).jpg",
  "assets/wallpapers/Windows_7_SP1_x64_Ultimate_Extreme Nature/Extreme Nature (40).jpg",
  "assets/wallpapers/Windows_7_SP1_x64_Ultimate_Extreme Nature/Extreme Nature (41).jpg",
  "assets/wallpapers/Windows_7_SP1_x64_Ultimate_Extreme Nature/Extreme Nature (42).jpg",
  "assets/wallpapers/Windows_7_SP1_x64_Ultimate_Extreme Nature/Extreme Nature (43).jpg",
  "assets/wallpapers/Windows_7_SP1_x64_Ultimate_Extreme Nature/Extreme Nature (44).jpg",
  "assets/wallpapers/Windows_7_SP1_x64_Ultimate_Extreme Nature/Extreme Nature (45).jpg",
  "assets/wallpapers/Windows_7_SP1_x64_Ultimate_Extreme Nature/Extreme Nature (46).jpg",
  "assets/wallpapers/Windows_7_SP1_x64_Ultimate_Extreme Nature/Extreme Nature (47).jpg",
  "assets/wallpapers/Windows_7_SP1_x64_Ultimate_Extreme Nature/Extreme Nature (48).jpg",
  "assets/wallpapers/Windows_7_SP1_x64_Ultimate_Extreme Nature/Extreme Nature (49).jpg",
  "assets/wallpapers/Windows_7_SP1_x64_Ultimate_Extreme Nature/Extreme Nature (5).jpg",
  "assets/wallpapers/Windows_7_SP1_x64_Ultimate_Extreme Nature/Extreme Nature (50).jpg",
  "assets/wallpapers/Windows_7_SP1_x64_Ultimate_Extreme Nature/Extreme Nature (51).jpg",
  "assets/wallpapers/Windows_7_SP1_x64_Ultimate_Extreme Nature/Extreme Nature (52).jpg",
  "assets/wallpapers/Windows_7_SP1_x64_Ultimate_Extreme Nature/Extreme Nature (53).jpg",
  "assets/wallpapers/Windows_7_SP1_x64_Ultimate_Extreme Nature/Extreme Nature (54).jpeg",
  "assets/wallpapers/Windows_7_SP1_x64_Ultimate_Extreme Nature/Extreme Nature (55).jpg",
  "assets/wallpapers/Windows_7_SP1_x64_Ultimate_Extreme Nature/Extreme Nature (56).jpg",
  "assets/wallpapers/Windows_7_SP1_x64_Ultimate_Extreme Nature/Extreme Nature (57).jpg",
  "assets/wallpapers/Windows_7_SP1_x64_Ultimate_Extreme Nature/Extreme Nature (58).jpg",
  "assets/wallpapers/Windows_7_SP1_x64_Ultimate_Extreme Nature/Extreme Nature (59).jpg",
  "assets/wallpapers/Windows_7_SP1_x64_Ultimate_Extreme Nature/Extreme Nature (6).jpg",
  "assets/wallpapers/Windows_7_SP1_x64_Ultimate_Extreme Nature/Extreme Nature (60).jpg",
  "assets/wallpapers/Windows_7_SP1_x64_Ultimate_Extreme Nature/Extreme Nature (61).jpg",
  "assets/wallpapers/Windows_7_SP1_x64_Ultimate_Extreme Nature/Extreme Nature (62).jpg",
  "assets/wallpapers/Windows_7_SP1_x64_Ultimate_Extreme Nature/Extreme Nature (63).jpg",
  "assets/wallpapers/Windows_7_SP1_x64_Ultimate_Extreme Nature/Extreme Nature (7).jpg",
  "assets/wallpapers/Windows_7_SP1_x64_Ultimate_Extreme Nature/Extreme Nature (8).jpg",
  "assets/wallpapers/Windows_7_SP1_x64_Ultimate_Extreme Nature/Extreme Nature (9).jpg",
  "assets/wallpapers/Winter.jpg",
  "assets/wallpapers/Yellow Moon.png"
];
